@startuml
ユーザ -> システム : ユーザ情報(email,password)
システム -> システム : ユーザ情報登録

alt 承認
  ユーザ <-- システム : マイページ取得
else 棄却
  ユーザ <-- システム : エラーメッセージ表示
  loop サインアップ成功まで
    ユーザ -> システム : ユーザ情報(email,password)
  end
end
@enduml