@startuml

alt メンバーを招待する
  ユーザ -> システム : メンバー追加
  システム -> 参照ユーザ : 通知
  システム --> ユーザ : 参照人数の変動(増)を確認
  alt メンバーとして参加する
    参照ユーザ -> システム : タスク参照
    システム --> 参照ユーザ : タスク取得
  else 参加しない
    参照ユーザ -> システム : 参照タスクを削除
    システム --> 参照ユーザ : 結果取得
    システム --> ユーザ : 参照人数の変動(減)を確認
  end
else メンバーを取り消す
  ユーザ -> システム : メンバー削除
  システム -> 参照ユーザ : タスク参照の権限失効を確認
  システム --> ユーザ : 削除処理完了の確認
end

@enduml