@startuml
scale 350 width

[*] --> トップページ

トップページ --> ログイン : ログイン/サインアップ

state ログイン {
  [*] --> ボード管理

  ボード管理 : ボードの閲覧/削除/編集
  ボード管理 ----> タスク : タスク作成
  ボード管理 --> ユーザ検索 : 招待ボタン押下（選択しているボードへユーザを招待）
  ボード管理 --> ボード管理 : ボードの編集
  ボード管理 --> [*] : ボード削除

  state タスク{
    [*] --> タスク管理
        タスク管理 : タスクの閲覧/削除/編集/状態を更新
        タスク管理 --> ユーザ検索 : 招待ボタン押下（現在のボードへユーザを招待）
        タスク管理 --> タスク管理 : タスクの編集/状態更新
        タスク管理 --> [*] : タスク削除
  }

   ユーザ検索 : 検索したユーザをボード/タスクに追加する
   ユーザ検索 --> ボード管理 : 追加完了
   ユーザ検索 --> タスク管理 : 追加完了
}

ログイン --------> [*] : ログアウト
@enduml